CREATE TABLE USERS(
   ID             INTEGER       PRIMARY KEY   AUTOINCREMENT   NOT NULL,
   FIRST_NAME     VARCHAR (30)  NOT NULL      UNIQUE,
   LAST_NAME      VARCHAR (30)  NOT NULL      UNIQUE,
   SHORT_NAME     VARCHAR (30)  NOT NULL      UNIQUE,
   IMAGE          VARCHAR (30)  NOT NULL,
   TAG            INTEGER       NULL
);
